apiVersion: v1
kind: Service
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sshd
  name: sshd
spec:
  ports:
  - name: "2222"
    port: 2222
    targetPort: 22
  selector:
    io.kompose.service: sshd
status:
  loadBalancer: {}
