apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: sshd
  name: sshd
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: sshd
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - chown -R root:root /etc/ssh && chmod 700 /etc/ssh && chmod 600 /etc/ssh/authorized_keys
          && chmod 600 /etc/ssh/ssh_host_ed25519_key && ls -lah /etc/ssh && /usr/sbin/sshd
          -D -f /etc/ssh/sshd_config -h /etc/ssh/ssh_host_ed25519_key
        image: terragraph/sshd:latest
        name: sshd
        ports:
        - containerPort: 22
        resources: {}
        volumeMounts:
        - mountPath: /etc/ssh
          name: sshd-claim0
      restartPolicy: Always
      volumes:
      - name: sshd-claim0
        persistentVolumeClaim:
          claimName: sshd-claim0
status: {}
