apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: db
  name: db
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: db
    spec:
      containers:
      - env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOST
              name: db-env-mysql-env
        - name: MYSQL_PASS
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASS
              name: db-env-mysql-env
        - name: MYSQL_ROOT_PASSWORD
          value: "12345"
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: db-env-mysql-env
        image: mysql:5
        name: db
        resources: {}
        volumeMounts:
        - mountPath: /docker-entrypoint-initdb.d
          name: db-claim0
          readOnly: true
        - mountPath: /var/lib/mysql
          name: db-claim1
      restartPolicy: Always
      volumes:
      - name: db-claim0
        persistentVolumeClaim:
          claimName: db-claim0
          readOnly: true
      - name: db-claim1
        persistentVolumeClaim:
          claimName: db-claim1
status: {}
