apiVersion: v1
data:
  GF_AUTH_ANONYMOUS_ENABLED: "true"
  GF_SERVER_ROOT_URL: '%(protocol)s://%(domain)s/grafana/'
  GRAFANA_ADMIN_PASS: test
  GRAFANA_DB: grafana
  GRAFANA_MYSQL_READER: grafanaReader
  GRAFANA_MYSQL_READER_PASS: uMDC36aagIUR
  GRAFANA_MYSQL_WRITER: grafanaWriter
  GRAFANA_MYSQL_WRITER_PASS: guHXwEDduo78
kind: ConfigMap
metadata:
  creationTimestamp: null
  labels:
    io.kompose.service: grafana-env-grafana-env
  name: grafana-env-grafana-env
