apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  annotations:
    kompose.cmd: kompose convert
    kompose.version: 1.16.0 (0c01309)
  creationTimestamp: null
  labels:
    io.kompose.service: jupyter
  name: jupyter
spec:
  replicas: 1
  strategy:
    type: Recreate
  template:
    metadata:
      creationTimestamp: null
      labels:
        io.kompose.service: jupyter
    spec:
      containers:
      - args:
        - /bin/sh
        - -c
        - jupyter notebook --no-browser --ip '0.0.0.0' --allow-root --port 8888 --notebook-dir
          /usr/local/analytics --NotebookApp.token='' --NotebookApp.base_url=jupyter
        env:
        - name: MYSQL_HOST
          valueFrom:
            configMapKeyRef:
              key: MYSQL_HOST
              name: jupyter-env-mysql-env
        - name: MYSQL_PASS
          valueFrom:
            configMapKeyRef:
              key: MYSQL_PASS
              name: jupyter-env-mysql-env
        - name: MYSQL_USER
          valueFrom:
            configMapKeyRef:
              key: MYSQL_USER
              name: jupyter-env-mysql-env
        image: secure.cxl-terragraph.com:443/analytics:latest
        name: jupyter
        resources: {}
        volumeMounts:
        - mountPath: /analytics/logs
          name: jupyter-claim0
      restartPolicy: Always
      volumes:
      - name: jupyter-claim0
        persistentVolumeClaim:
          claimName: jupyter-claim0
status: {}
